// Auto-generated embedded model data for retinaface
// DO NOT EDIT - Generated by tools/convert_model_to_cpp.py

#ifndef FACEID_DETECTORS_RETINAFACE_MODEL_DATA_H
#define FACEID_DETECTORS_RETINAFACE_MODEL_DATA_H

#include <cstddef>
#include <cstdint>

namespace faceid {
namespace embedded {

// retinaface model binary data
extern const uint8_t retinaface_model_bin[];
extern const size_t retinaface_model_bin_size;

// retinaface model param data (text format)
extern const char retinaface_model_param[];
extern const size_t retinaface_model_param_size;

} // namespace embedded
} // namespace faceid

#endif // FACEID_DETECTORS_RETINAFACE_MODEL_DATA_H
