// Auto-generated embedded model data for yunet
// DO NOT EDIT - Generated by tools/convert_model_to_cpp.py

#ifndef FACEID_DETECTORS_YUNET_MODEL_DATA_H
#define FACEID_DETECTORS_YUNET_MODEL_DATA_H

#include <cstddef>
#include <cstdint>

namespace faceid {
namespace embedded {

// yunet model binary data
extern const uint8_t yunet_model_bin[];
extern const size_t yunet_model_bin_size;

// yunet model param data (text format)
extern const char yunet_model_param[];
extern const size_t yunet_model_param_size;

} // namespace embedded
} // namespace faceid

#endif // FACEID_DETECTORS_YUNET_MODEL_DATA_H
