#!/usr/bin/env python3
"""
Convert NCNN model files (.param and .bin) to embedded C++ arrays.
Inspired by libfacedetection's approach to embed models directly in source code.

Usage:
    python3 convert_model_to_cpp.py <model_name> <param_file> <bin_file> <output_dir>

Example:
    python3 convert_model_to_cpp.py yunet models/yunet.param models/yunet.bin src/detectors/
"""

import sys
import os
from pathlib import Path


def generate_header(model_name: str, bin_size: int, param_lines: int) -> str:
    """Generate C++ header file content."""
    guard = f"FACEID_DETECTORS_{model_name.upper()}_MODEL_DATA_H"

    return f"""// Auto-generated embedded model data for {model_name}
// DO NOT EDIT - Generated by tools/convert_model_to_cpp.py

#ifndef {guard}
#define {guard}

#include <cstddef>
#include <cstdint>

namespace faceid {{
namespace embedded {{

// {model_name} model binary data
extern const uint8_t {model_name}_model_bin[];
extern const size_t {model_name}_model_bin_size;

// {model_name} model param data (text format)
extern const char {model_name}_model_param[];
extern const size_t {model_name}_model_param_size;

}} // namespace embedded
}} // namespace faceid

#endif // {guard}
"""


def generate_source(model_name: str, param_data: bytes, bin_data: bytes) -> str:
    """Generate C++ source file content with embedded arrays."""

    # Convert param data to C string (escape special characters)
    param_str = param_data.decode("utf-8")
    param_str = (
        param_str.replace("\\", "\\\\").replace('"', '\\"').replace("\n", '\\n"\n    "')
    )

    # Generate binary array with proper formatting (16 bytes per line)
    bin_lines = []
    for i in range(0, len(bin_data), 16):
        chunk = bin_data[i : i + 16]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        bin_lines.append(f"    {hex_bytes}")

    bin_array_str = ",\n".join(bin_lines)

    return f"""// Auto-generated embedded model data for {model_name}
// DO NOT EDIT - Generated by tools/convert_model_to_cpp.py

#include "{model_name}_model_data.h"

namespace faceid {{
namespace embedded {{

// {model_name} model binary data ({len(bin_data)} bytes)
const uint8_t {model_name}_model_bin[] = {{
{bin_array_str}
}};

const size_t {model_name}_model_bin_size = sizeof({model_name}_model_bin);

// {model_name} model param data ({len(param_data)} bytes)
const char {model_name}_model_param[] = 
    "{param_str}";

const size_t {model_name}_model_param_size = sizeof({model_name}_model_param) - 1;  // Exclude null terminator

}} // namespace embedded
}} // namespace faceid
"""


def convert_model(model_name: str, param_file: str, bin_file: str, output_dir: str):
    """Convert NCNN model files to C++ embedded arrays."""

    # Read input files
    print(f"Reading {param_file}...")
    with open(param_file, "rb") as f:
        param_data = f.read()

    print(f"Reading {bin_file}...")
    with open(bin_file, "rb") as f:
        bin_data = f.read()

    print(f"  Param size: {len(param_data):,} bytes")
    print(f"  Binary size: {len(bin_data):,} bytes")
    print(f"  Total: {len(param_data) + len(bin_data):,} bytes")

    # Generate output files
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    header_path = output_dir / f"{model_name}_model_data.h"
    source_path = output_dir / f"{model_name}_model_data.cpp"

    print(f"\nGenerating {header_path}...")
    header_content = generate_header(model_name, len(bin_data), len(param_data))
    with open(header_path, "w") as f:
        f.write(header_content)

    print(f"Generating {source_path}...")
    source_content = generate_source(model_name, param_data, bin_data)
    with open(source_path, "w") as f:
        f.write(source_content)

    print(f"\n✓ Successfully generated embedded model data for '{model_name}'")
    print(f"  - {header_path}")
    print(f"  - {source_path}")

    # Calculate estimated compiled size (rough approximation)
    estimated_size = len(bin_data) + len(param_data) + (len(bin_data) // 2)
    print(f"\n  Estimated compiled size increase: ~{estimated_size / 1024:.1f} KB")


def main():
    if len(sys.argv) != 5:
        print(
            "Usage: convert_model_to_cpp.py <model_name> <param_file> <bin_file> <output_dir>"
        )
        print("\nExample:")
        print(
            "  python3 convert_model_to_cpp.py yunet models/yunet.param models/yunet.bin src/detectors/"
        )
        sys.exit(1)

    model_name = sys.argv[1]
    param_file = sys.argv[2]
    bin_file = sys.argv[3]
    output_dir = sys.argv[4]

    # Validate input files
    if not os.path.exists(param_file):
        print(f"Error: Param file not found: {param_file}")
        sys.exit(1)

    if not os.path.exists(bin_file):
        print(f"Error: Binary file not found: {bin_file}")
        sys.exit(1)

    convert_model(model_name, param_file, bin_file, output_dir)


if __name__ == "__main__":
    main()
